sudo: true
language: ruby
rvm:
- 2.3.4
#cache:
#  bundler: true
env:
  global:
    # GIT_N=<git name> GIT_E=<git email> GH_U=<github username> GH_T=<oauth token>   DOCKER_USERNAME= DOCKER_PASSWORD=
    - secure: K+5gZFwJ5lyh1CJpifiRPBuXNagvg2GH+4eetn5mSSS/fA2qvkuoN8O6Vq+Rdg1hUWNnWL+Ck/c0D67IhW0J1EIz92FoFLCniLTSm5+BZC3cJhTRQdiTVf0tDsDnmtToexJGhWJ/Fg3iY37sjtA4+uBQg6nZ3pmFikGejZYE79AaevJp+az9XvUrCHegGchT/YjaINa/EKcKFzfMipPEZTkPO8YMl7pkIVKEHj8ASn+e6s88/ISRQED2YuDwAs+t9kekQl6qUSaSyPXiX4AFgi8e28ZA7P/dnLCe5mlFeFx2jaXilc+2W1asb/pJ9SmZO8egn8ONoB9cXfXDxo/zue87OO/vSicVGKmWcJruzU0/awyh2QNORp+LfxZdSXiuBR9dG7CpKOQoF8P4wf7yDp2yZewftFJKjQG6aSvKbRksdPPxyGgyti7p31yOVJhmy847OWann9uprs+ocG/VY8qnYCODeTrGrJgy8elYLEQNP9s32GzDVTdTAVg527Hp9k7/FMteSWGqvxUttkX6Z8grMnB+Ivf5cuhj1Bm+RHiqrIlDea3y48nQPha33lU8XOMZnLPeixl/xgACVvHLywJxCswzhuGBo9PlUs/hYXvWXAbxzq2yk5Ihys0M99G6xJvKrV/xr1ZhnD9KyZUGKXmM8VPYykIRFjCzSyjNYnI=
    # speeds up Nokogiri installation
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
git:
  depth: 1
branches:
  only:
    - master
install:
  - sudo apt-get install -qq graphviz
before_script:
  - bundle install
script: bundle exec rake travis
services:
  - docker
after_script:
    - docker build -t asciidoctor-builder:1.5.4 -t asciidoctor-builder:latest -f Dockerfile .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push asciidoctor-builder:1.5.4
    - docker push asciidoctor-builder:latest
